baseURL = "https://bentsukun.ch"
languageCode = "en-us"
title = "benzblog"
theme = "purehugo"
Paginate = 10

[taxonomies]
category = "categories"

[params]
githubName = "bsiegert"
fediverseAddress = "mastodon.sdf.org/@bentsukun"
googleplus = false
twitter = false
hideShareOptions = true

[markup]
[markup.highlight]
style = "github"
