baseURL = "https://bentsukun.ch"
languageCode = "en-us"
title = "benzblog"
theme = "purehugo"


[pagination]
pagerSize = 10

[taxonomies]
category = "categories"

[params]
githubName = "bsiegert"
fediverseAddress = "mastodon.sdf.org/@bentsukun"
googleplus = false
twitter = false
hideShareOptions = true
additionalLinks.Talks = "/talks"

[markup]
[markup.highlight]
style = "github"
# Delete this bit after removing the Twitter embeds
[markup.goldmark.renderer]
unsafe = true
