baseURL = "https://bentsukun.ch"
languageCode = "en-us"
title = "benzblog"
theme = "purehugo"
Paginate = 10

[taxonomies]
category = "categories"

[params]
twitterName = "bentsukun"
githubName = "bsiegert"
googleplus = false
twitter = false
hideShareOptions = true
